server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: hotelModule
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**
        - id: userModule
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: ratingModule
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**